import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { EventList } from "../../components/events/event-list";
import ResultsTitle from "../../components/events/results-title";
import { Button } from "../../components/ui/button";
import ErrorAlert from "../../components/ui/error-alert";
import { getFilteredEvents } from "../../dummy-data";

export default function FilteredEventsPage() {
  const router = useRouter();
  const filterData = router?.query?.slug;
  if (!filterData) {
    return <p className="center">Loading...</p>;
  }

  const filteredYear = filterData[0];
  const filteredMonth = filterData[1];

  const numYear = +filteredYear;
  const numMonth = +filteredMonth;

  if (
    isNaN(filteredYear) ||
    isNaN(filteredMonth) ||
    filteredYear < 2021 ||
    filteredYear > 2023 ||
    filteredMonth < 1 ||
    filteredMonth > 12
  ) {
    return (
      <>
      <ErrorAlert>
      <p>Invalid Filter, Please adjust you values!</p>

      </ErrorAlert>
        <div className="center">
          <Button link={"/events"}> Show All Events</Button>
        </div>
      </>
    );
  }

  const filteredEvents = getFilteredEvents({
    year: numYear,
    month: numMonth,
  });
  if (!filteredEvents || filteredEvents.length === 0) {
    return (
      <>
        <p>No Events found for the chosen filter</p>

        <div className="center">
          <Button link={"/events"}> Show All Events</Button>
        </div>
      </>
    );
  }
  const date = new Date(numYear, numMonth - 1);
  console.log(date, numMonth);
  return (
    <>
      <Head>
        <title>Filtered Events Page</title>
        <meta name="description" content="Generated by Filtered Events Page" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ResultsTitle date={date} />
      <EventList items={filteredEvents} />
    </>
  );
}
