import Head from "next/head";
import { useRouter } from "next/router";
import { EventList } from "../../components/events/event-list";
import EventSearch from "../../components/events/event-search";
import { getAllEvents } from "../../dummy-data";

export default function AllEventsPage() {
  const events = getAllEvents();
  const router = useRouter()

  const findEventsHandler = (year, month) => {
    const fullPath = `/events/${year}/${month}`
    router.push(fullPath)
    console.log(year);
    console.log(month);
  };
  return (
    <>
      <Head>
        <title>Event Page</title>
        <meta name="description" content="Generated by Event  Page" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <EventSearch onSearch={findEventsHandler} />
        <EventList items={events} />
      </div>
    </>
  );
}
