import Head from "next/head";
import { EventList } from "../components/events/event-list";
import { getFeaturedEvents } from "../dummy-data";
import styles from "../styles/Home.module.scss";

export default function HomePage() {
const featuredEvents = getFeaturedEvents()
  return (
    <div className={styles.container}>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by Home Page" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <EventList items={featuredEvents}/>
      </main>
    </div>
  );
}
